---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 5/2/20 12:57 AM
---

local RPD = require "scripts/lib/commonClasses"

local storage = require "scripts/lib/storage"

local gameScene = {}

local prevTime = 0.

gameScene.onStep = function()
if storage.get("functions") then
storage.get("functions")()
end
end

gameScene.selectCell = function()
end

return gameScene
