---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 5/2/20 12:57 AM
---

local t = 0

local RPD = require("scripts/lib/epicClasses")

local gameScene = {
onStep = function()
t = t + 1
for _,i in pairs(RPD.functions) do
i(t)
end
if t >= 100 then
t = 0
end
end,
selectCell = function()
end
}
return gameScene
