---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 9/25/21 7:41 PM
---

local RPD = require "scripts/lib/commonClasses"

local object = require "scripts/lib/object"

local DungeonTileMap = luajava.bindClass("com.watabou.pixeldungeon.DungeonTilemap")

return object.init{
    stepOn = function(self, object, hero)
        return true
    end,
    addedToScene = function(self, object)
    		local p = DungeonTileMap:tileCenterToWorld(object:getPos())
    		
    		local Halo = RPD.new("com.watabou.pixeldungeon.effects.Halo",5,0xffffff,0.1)
    		Halo:point(p.x-2,p.y-2)
    		RPD.GameScene:effect(Halo)
    		local Halo = RPD.new("com.watabou.pixeldungeon.effects.Halo",5,0xffffff,0.1)
    		Halo:point(p.x+2,p.y-2)
			RPD.GameScene:effect(Halo)
			
			local emitter = RPD.Sfx.CellEmitter:get(object:getPos())
			emitter:pos(p.x-2,p.y-2,0.01,0.01)
			emitter:pour(RPD.Sfx.ElmoParticle.FACTORY, 0.2)
			
			local emitter = RPD.Sfx.CellEmitter:get(object:getPos())
			emitter:pos(p.x+2,p.y-2,0.01,0.01)
			emitter:pour(RPD.Sfx.ElmoParticle.FACTORY, 0.2)

    end
}