local table = 
{
kind = "Castle",
Entrance = "CavesEntrance",
EntranceDebag = "EntranceDebag",
Exit = "CavesExit",
ExitHeigth = 4,
ExitWidth = 4,
RoomHeigth = 7,
RoomWidth = 7, 
RandRooms = {"GooRoom","GooSloth","GooBalls","GooLibrary","BigGooLibrary","GooArmory","GooEye","GooChaos","GooWarehause","GooChasm","GooTomb","GooFishbowl","GooStatue","GooTeeth","GooBestRoom","GooBestRoom","GooBestRoom"},
--RandRooms = {"SpinnerNest"},
HasBase = true,
Water = true,
WaterMin = 1,
WaterMax = 3,
WaterChanse = 0.0005,
Grass = true,
GrassChanse = 0.0001,
GrassMin = 1,
GrassMax = 2,
Traps = {
"ToxicTrap",
"FireTrap",
"PoisonTrap",
"AlaramTrap",
"GrippingTrap",
"LightingTrap",
"ParalyticTrap",
"SecretToxicTrap",
"SecretFireTrap",
"SecretPoisonTrap",
"SecretAlaramTrap",
"SecretGrippingTrap",
"SecretLightingTrap",
"SecretParalyticTrap"
},
ChanseTrap = 0.1,
Shop = "GooShop",
LevelShop = 21,
ShopWidth = 7,
ShopHeigth = 7,
NPC = nil,
levelNPC = 22,
NPCRoom = "GooWitchRoom",
NPCRoomWidth = 7,
NPCRoomHeigth = 7,
GinFactor = 20,
RoomFactor = 0,
MiniBoss = {"BookshelfMonsterRoom","GooHashRoom"},
LevelMiniBoss = 24
}

return table
