local table = 
{
kind = "Castle",
Entrance = "Entrance",
EntranceDebag = "EntranceDebag",
Exit = "BigExit",
ExitHeigth = 4,
ExitWidth = 4,
RoomHeigth = 9,
RoomWidth = 9,
RandRooms = {"IceCastleArmory","IceElementals","IceCastleIceGaurds","AirIceCastleLibrary","BigIceCastleLibrary","IceGolems","IceCastleStatue","IceCastleLibrary","IceCastleTomb","IceCastleChasm","IceCastleRiches","IceCastleRiches","IceCastleRiches","IceCastleFishbowl","IceCastleWell","IceCastleAir","IceCastleHell"},
-- RandRooms = {"PrisonArmory"},
HasBase = false,
Items = {"Ration"},
Water = true,
WaterMin = 1,
WaterMax = 2,
WaterChanse = 0.0005,
Grass = true,
GrassChanse = 0.0001,
GrassMin = 1,
GrassMax = 2,
Traps = {
"ToxicTrap",
"FireTrap",
"PoisonTrap",
"AlaramTrap",
"GrippingTrap",
"LightingTrap",
"ParalyticTrap",
"SecretToxicTrap",
"SecretFireTrap",
"SecretPoisonTrap",
"SecretAlaramTrap",
"SecretGrippingTrap",
"SecretLightingTrap",
"SecretParalyticTrap"
},
ChanseTrap = 0.1,
Shop = "IceCastleShop",
LevelShop = 26,
ShopWidth = 7,
ShopHeigth = 7,
NPC = nil,
levelNPC = 28,
NPCRoom = "SpiritIntoIceRoom",
NPCRoomWidth = 7,
NPCRoomHeigth = 7,
Range = 10000,
GinFactor = 20,
RoomFactor = 0,
MiniBoss = {"StatueOfDemonRoom"},
LevelMiniBoss = 29
}

return table
