local table = 
{
kind = "Caves",
Entrance = "CavesEntrance",
EntranceDebag = "EntranceDebag",
Exit = "CavesExit",
ExitHeigth = 4,
ExitWidth = 4,
RoomHeigth = 7,
RoomWidth = 7, 
RandRooms = {"WaterCave","BigWaterCave","SmallWaterCave","WaterCavesShasm","GnollLibersPost","WaterCavesLibrary","WaterCavesFishbowl","HydraNest","WaterZombieRoom","WaterCavesBestRoom","WaterCavesBestRoom","WaterCavesBestRoom","WaterCavesRuins","ToxicRotHeartRoom","WaterOfiuraRoom","WaterCavesStatueRoom"},
HasBase = false,
Items = {"Ration"},
Water = true,
WaterMin = 1,
WaterMax = 1,
WaterChanse = 1,
Traps = {
"ToxicTrap",
"FireTrap",
"PoisonTrap",
"AlaramTrap",
"GrippingTrap",
"LightingTrap",
"ParalyticTrap",
"SecretToxicTrap",
"SecretFireTrap",
"SecretPoisonTrap",
"SecretAlaramTrap",
"SecretGrippingTrap",
"SecretLightingTrap",
"SecretParalyticTrap"
},
ChanseTrap = 0.1,
Shop = "WaterCavesShop",
LevelShop = 16,
ShopWidth = 7,
ShopHeigth = 7,
NPC = nil,
levelNPC = 17,
NPCRoom = "ArchaeologistRoom",
NPCRoomWidth = 7,
NPCRoomHeigth = 7,
Range = 10000,
GinFactor = 20,
RoomFactor = 0,
MiniBoss = {"GorgonsHeadRoom"},
LevelMiniBoss = 19
}

return table
