---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 23.08.18 22:51
---

local RPD = require "scripts/lib/epicClasses"

local ai = require "scripts/lib/ai"

return ai.init{

act       = function(self, ai, me)

addSkeleton = function()
local level = RPD.Dungeon.level
local x = level:cellX(me:getPos())
local y = level:cellY(me:getPos())
for i = x - 4, x + 4 do
for j = y - 4, y + 4 do
local pos = RPD.Dungeon.level:cell(i,j)
if level.map[pos] == RPD.Terrain.PEDESTAL then
mob = RPD.MobFactory:mobByName("WitherSkeleton")
local level = RPD.Dungeon.level
mob:setPos(pos-1)
level:spawnMob(mob)
me:spend(3)
end
end
end
me:getSprite():dummyAttack()
end

addRay = function()
local level = RPD.Dungeon.level

ray = function(cell)
local from = level:cellX(cell)
local to = cell
local enemy = RPD.Actor:findChar(to)
RPD.zapEffect(from,to,"DeathRay")
if enemy and enemy ~= me then
enemy:damage(math.random(10,20),me)
end
end

local x = level:cellX(me:getPos())
local y = level:cellY(me:getPos())
for i = x - 4, x + 4 do
for j = y - 4, y + 4 do
local pos = RPD.Dungeon.level:cell(i,j)
if level.map[pos] == RPD.Terrain.EMPTY_SP and math.random(1,6) == 1 then
ray(pos-1)
end
end
end
me:getSprite():dummyAttack()
end

if math.random(1,4) == 1 then
addSkeleton()
else
addRay()
me:spend(1)
end

end,

    gotDamage = function(self, ai, me, src, dmg)

    end,

    status = function(self, ai, me)
        return RPD.StringsManager:maybeId("attack_on_you")
    end
}