---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 23.08.18 22:51
---

local RPD = require "scripts/lib/epicClasses"

local ai = require "scripts/lib/ai"

local EPD = require "scripts/lib/dopClasses"

local t = 0

return ai.init{

    act       = function(me, ai, me)
t = t + 1
for i =0, #RPD.functions do
RPD.functions[i](t)
end
if t % 30 == 0 then
me:die()
t = 0
end
end,

    gotDamage = function(me, ai, me, src, dmg)
end,

    status = function(me, ai, me)
        return (me:getName()..RPD.StringsManager:maybeId("ai_mob_attack")..f:getName())
    end
}
