---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 12/21/19 11:56 PM
---

local RPD  = require "scripts/lib/epicClasses"

local buff = require "scripts/lib/buff"

local flame = {"Fire", "LiquidFlame","Burning"}

return buff.init{
    desc  = function ()
        return {
            icon          = -1,
            name          = "GasesImmunity_Info",
            info          = "GasesImmunity_Info",
        }
    end,

    immunities = function(self, buff)
        return flame
    end

}