---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 25.03.19 0:06
---

local buff = require "scripts/lib/buff"

local RPD = require "scripts/lib/epicClasses"

return buff.init{
    desc  = function ()
        return {
            icon          = 5,
            name          = RPD.StringsManager:maybeId("LightShild_Buff"),
            info          = "BodyArmorBuff_Info",
         }
    end,
    textureLarge = function()
    return "ui/CustomBuffsLarge.png"
    end,
    textureSmall = function()
    return "ui/CustomBuffs.png"
    end,
    act = function(self,buff)
        buff:detach()
    end,
    drBonus = function(self,buff)
        return 1000000
    end
    }
