---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 23.08.18 22:51
---

local RPD     = require "scripts/lib/epicClasses"

local ai      = require "scripts/lib/ai"

local storage = require "scripts/lib/storage"

local Process = require "scripts/lib/Process"

return ai.init {

    act       = function(self, ai, me)

        local hPos  = RPD.Dungeon.hero:getPos()
        local myPos = me:getPos()

        if RPD.Dungeon.level:distance(hPos, myPos) < 4 then
            me:beckon(hPos)
        else
            local mySprite = me:getSprite()
            if Process.golden_gaurd_pos then
                if mySprite then
                    mySprite:move(myPos, Process.golden_gaurd_pos)
                    mySprite:idle()
                end
                me:move(Process.golden_gaurd_pos)
                me:spend(1)
            end
        end
    end,

    gotDamage = function(self, ai, me, src, dmg)
    end,

    status    = function(self, ai, me)
        return RPD.StringsManager:maybeId("attack_on_you")
    end
}