---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 23.08.18 22:51
---

local RPD = require "scripts/lib/epicClasses"

local ai = require "scripts/lib/ai"

local EPD = require "scripts/lib/dopClasses"

return ai.init{

    act       = function(self, ai, me)
        me:spend(1)
    end,

    gotDamage = function(self, ai, me, src, dmg)
        if src.getPos then
            me:beckon(src:getPos())
        end
    end,

    status = function(me, ai, me)
        return RPD.StringsManager:maybeId("Mob_StaSleepingStatus",me)
    end
}