---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 29.12.18 23:48
---

local RPD = require "scripts/lib/epicClasses"

local trap = require"scripts/lib/trap"

local Badges = luajava.bindClass("com.watabou.pixeldungeon.Badges")

local dialog1 = function(index)
    if index == 0 then
Badges:validateItemLevelAcquired("ShortSword");
else
RPD.glog("nethe")
        return
    end
end

return trap.init(
        function (cell, char, data)

            RPD.chooseOption( dialog1,
                    RPD.StringsManager:maybeId("MagicBook_Name"),
                    RPD.StringsManager:maybeId("MagicBook_Info"),
                    RPD.StringsManager:maybeId("MagicBook_Spells"))
                end
)
