---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 21.03.19 22:08
---

local spells = {}
spells["Necromancy"] = {"RaiseDead","Exhumation", "DarkSacrifice","ManaBeorn","RaiseSoul","SummonSoul","SummonSkvernSoul","SummonDarkSoul"}
spells["Elemental"] = {"ElementalSpell","NetherFire"}

return spells