---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 23.08.18 22:51
---

local RPD = require "scripts/lib/epicClasses"

local ai = require "scripts/lib/ai"

return ai.init{

act       = function(self, ai, me)
me:getSprite():idle()
if RPD.Dungeon.level:distance(RPD.Dungeon.hero:getPos(),me:getPos()) < 5 then

top = function(from,to)
local mob = RPD.mob("effects/Boll") 
mob:setPos(from)
RPD.Dungeon.level:spawnMob(mob)
local factor = RPD.Dungeon.level:distance(from,to)
RPD.Tweeners.JumpTweener:attachTo(mob:getSprite(),to, factor * 7,factor * 0.1f)
mob:getSprite():emitter():start(RPD.Sfx.ElmoParticle.FACTORY, 0.01,factor*10+1)
mob:destroy()
end

bottom = function(from,to)
local mob = RPD.mob("effects/Boll") 
mob:setPos(from)
RPD.Dungeon.level:spawnMob(mob)
local factor = RPD.Dungeon.level:distance(from,to)
RPD.Tweeners.JumpTweener:attachTo(mob:getSprite(),to, factor *7*-1,factor * 0.1f)
mob:getSprite():emitter():start(RPD.Sfx.ElmoParticle.FACTORY, 0.01,factor*10+1)
mob:destroy()
end

center = function(from,to)
missile = me:getSprite():getParent():recycle(RPD.Sfx.MagicMissile)
missile:reset( from,to,nil)
missile:size(8)
missile:pour( RPD.Sfx.ElmoParticle.FACTORY, 0.01)
end

effect = function(from,to)
if math.random(1,2) == 1 then
top(from,to)
elseif math.random(1,2) == 1 then
center(from,to)
else
bottom(from,to)
end
end

removeObj = function(cell)
local level = RPD.Dungeon.level
local object = level:getTopLevelObject(cell)
if object then
level:remove(object)
object.sprite:kill()
end
end

addStatue = function(cell)
local maybeMob = RPD.mob("SumStatue")
maybeMob:setPos(cell)
RPD.Dungeon.level:spawnMob(maybeMob)
maybeMob:getSprite():emitter():burst( RPD.Sfx.ElmoParticle.FACTORY, 5)
end

summon = function(cell)
local from = me:getPos()
local to = RPD.Ballistica:cast(from,cell,true,true,true)
local enemy = RPD.Actor:findChar(to)
if enemy and enemy ~= me then
enemy:damage(math.random(30,50),me)
effect(from,to)
return
end
local level = RPD.Dungeon.level
local object = level:getTopLevelObject(cell)
if object then
object.sprite:kill()
level:remove(object)
end
RPD.GameScene:updateMap(cell)
effect(from,cell)
removeObj(cell)
addStatue(cell)
end


local level = RPD.Dungeon.level
local x = level:cellX(me:getPos())
local y = level:cellY(me:getPos())
for i = x - 3, x + 3 do
for j = y - 3, y + 3 do
local pos = RPD.Dungeon.level:cell(i,j)
local object = level:getTopLevelObject(pos)
if object then
if math.random(1,16) == 1 then
summon(pos)
me:getSprite():attack(1)
RPD.playSound( "snd_zap.mp3" )
end
end
end
end

end

me:spend(math.random(1,4))
end,

    gotDamage = function(self, ai, me, src, dmg)

    end,

    status = function(self, ai, me)
        return RPD.StringsManager:maybeId("attack_on_you")
    end
}