local table = 
{
kind = "Town",
Entrance = "CityEntrance",
EntranceDebag = "EntranceDebag",
Exit = "CityExit",
ExitHeigth = 4,
ExitWidth = 4,
RoomHeigth = 11,
RoomWidth = 11,
RandRooms = {"CityTemple","CityFishbowl","GolemWorkshop","CityStreet1","CityGarden","CityHause","CityGuards","CityChurch","CityArmory","CityLibrary","CaseRoom","CityRiches","CityArmory2","DworfKingStatue","CitySewer","BigCitySewer","CityChasm","CityNecropolis"},
-- RandRooms = {"PrisonArmory"},
HasBase = false,
Items = {"Ration"},
Water = true,
WaterMin = 1,
WaterMax = 3,
WaterChanse = 0.0005,
Grass = true,
GrassChanse = 0.0001,
GrassMin = 1,
GrassMax = 2,
Traps = {
"ToxicTrap",
"FireTrap",
"PoisonTrap",
"AlaramTrap",
"GrippingTrap",
"LightingTrap",
"ParalyticTrap",
"SecretToxicTrap",
"SecretFireTrap",
"SecretPoisonTrap",
"SecretAlaramTrap",
"SecretGrippingTrap",
"SecretLightingTrap",
"SecretParalyticTrap"
},
ChanseTrap = 0.1,
Chanse = 1,
Shop = "CityShop",
LevelShop = 16,
ShopWidth = 9,
ShopHeigth = 9,
NPC = nil,
levelNPC = 17,
NPCRoom = "CityPortal",
NPCRoomWidth = 7,
NPCRoomHeigth = 7,
Range = 10000,
GinFactor = 20,
RoomFactor = 0,
MiniBoss = nil,
LevelMiniBoss = nil
}

return table