---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 04.08.18 18:14
---

local RPD = require "scripts/lib/commonClasses"

local actor = require "scripts/lib/actor"

local storage = require "scripts/lib/storage"

return actor.init({
    actionTime = function()
        return 1
    end,
    activate = function()
RPD.removeBuff(RPD.Dungeon.hero, "ModBuff");
RPD.permanentBuff(RPD.Dungeon.hero, "ModBuff");


local effect = RPD.MobFactory:mobByName("effects/Light")
effect:setPos(335)
RPD.Dungeon.level:spawnMob(effect)
effect:move(2)
RPD.createLevelObject({
    kind="Deco",
    object_desc="Light"
}
,335)
local effect = RPD.MobFactory:mobByName("effects/Light")
effect:setPos(596)
RPD.Dungeon.level:spawnMob(effect)
effect:move(2)
RPD.createLevelObject({
    kind="Deco",
    object_desc="Light"
}
,596)
local effect = RPD.MobFactory:mobByName("effects/Light")
effect:setPos(358)
RPD.Dungeon.level:spawnMob(effect)
effect:move(2)
RPD.createLevelObject({
    kind="Deco",
    object_desc="Light"
}
,358)
local effect = RPD.MobFactory:mobByName("effects/Light")
effect:setPos(250)
RPD.Dungeon.level:spawnMob(effect)
effect:move(2)
RPD.createLevelObject({
    kind="Deco",
    object_desc="Light"
}
,250)
local effect = RPD.MobFactory:mobByName("effects/Light")
effect:setPos(787)
RPD.Dungeon.level:spawnMob(effect)
effect:move(2)
RPD.createLevelObject({
    kind="Deco",
    object_desc="Light"
}
,787)

        local levelSize = RPD.Dungeon.level:getLength()
        for i = 0 , levelSize - 1 do
            if RPD.Dungeon.level.solid[i] then
                local emitter = RPD.Sfx.CellEmitter:get(i)
                --emitter:pour(RPD.Sfx.SnowParticle.FACTORY, 2)
            end
        end

    end,
act = function()
return true
end
})