---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 25.03.19 0:00
---


local buffs = {
-- common

"DieHard",
"FireBless",
"WaterRegeneration",
"Greed",
"Counter",
"MagicFire",

-- mehanic
"ModBuff",
"Gun",
"Helmet",

-- artifacts buffs
"HolyMantel",
"DarckMantel",
"LightShild",
"Luck",
"IceSkull",

-- wands buffs
"Summoners",
"Poison",
"Earth",
"Lighting",
"Mirror",
"Posses",
"Rock",

-- ai buffs
"FollowMe",
"Attacher",
"Ratcatcher",
"Guard",

-- multiplayer
"Multiplayer_host",
"Multiplayer_player",

-- hero classes

-- potions
"FireCandle"
}

return buffs
