---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 9/25/21 7:41 PM
---

local RPD = require "scripts/lib/commonClasses"

local object = require "scripts/lib/object"

local DungeonTileMap = luajava.bindClass("com.watabou.pixeldungeon.DungeonTilemap")

return object.init{
    stepOn = function(self, object, hero)
        return true
    end,
    addedToScene = function(self, object)
        local Halo = RPD.new("com.watabou.pixeldungeon.effects.Halo",14,0xffffff,0.1)
        Halo:point(DungeonTileMap:tileCenterToWorld(object:getPos()).x,DungeonTileMap:tileCenterToWorld(object:getPos()).y-4)
        RPD.GameScene:effect(Halo)
    end
}