---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 9/25/21 7:41 PM
---

local RPD = require "scripts/lib/commonClasses"

local object = require "scripts/lib/object"

local DungeonTileMap = luajava.bindClass("com.watabou.pixeldungeon.DungeonTilemap")

return object.init{

    bump = function(self, object, presser)
        local soul = RPD.Actor:findChar(object:getPos())
        if soul ~= presser then
            local mob = RPD.mob("YellowGoo")
            mob:setPos(object:getPos())
            local tile =
            {
                kind="CustomObject",
                object_desc="BrokenLamp"
            }
            RPD.createLevelObject(tile,object:getPos())
            local heap = RPD.Dungeon.level:getHeap(object:getPos())
            local item = heap:peek()
            heap:pickUp()
            mob:loot(item)
            RPD.setAi(mob,"Hunting")
            RPD.Dungeon.level:spawnMob(mob)
            object.sprite:kill()
            RPD.Dungeon.level:remove(object)
            RPD.playSound("snd_shatter")
            local Splash = luajava.bindClass("com.watabou.pixeldungeon.effects.Splash")
            Splash.at(RPD.Dungeon.hero:getSprite():emitter(),object:getPos(),0xFFBB0000, 6)
        end
    end
}