---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 04.08.18 18:14
---

local RPD = require "scripts/lib/commonClasses"

local actor = require "scripts/lib/actor"

local storage = require "scripts/lib/storage"

local Multiplayer = require"scripts/lib/Multiplayer"

local User = require"scripts/lib/User"

local dungeonEntrance = {13, 4}
local shopEntrance    = {18, 16}

local lastWarningTime = 0
local time = 0

return actor.init({
    actionTime = function()
        return 1
    end,
    activate = function()
local select = function(ind)
if ind == 0 then
storage.put("multiplayer",true)
end
if ind == 1 then
storage.put("multiplayer",false)
end
end
--[[
RPD.chooseOption( 
select,
"Хотите включить отображение других игроков на этом уровне?",
"Этот режим ещё в стадии разработки. Вы будите видеть других игроков.",
"Да",
"Нет"
)
--]]

if not storage.get("nik") then
select_nik = function(index)
if index == 0 then
RPD.System.Input:showInputDialog("Сохранение ника", ("Введите свой ник, ваш текущий ник "..User.player))
RPD.chooseOption( 
select_nik,
("Ваш ник: "..User.player),
"Выберите функцию",
"Изменить",
"Сохранить изменения"
)
end
if index == 1 then
User.player = RPD.System.Input:getInputString()
storage.gamePut("nik",User.player)
RPD.chooseOption( 
select_nik,
("Ваш ник: "..User.player),
"Выберите функцию",
"Изменить",
"Сохранить изменения"
)
end
end
RPD.chooseOption( 
select_nik,
("Ваш ник: "..User.player),
"Выберите функцию",
"Изменить",
"Сохранить изменения"
)
end
storage.put("nik",true)



RPD.removeBuff(RPD.Dungeon.hero, "ModBuff");
RPD.permanentBuff(RPD.Dungeon.hero, "ModBuff");


local effect = RPD.MobFactory:mobByName("effects/Light")
effect:setPos(335)
RPD.Dungeon.level:spawnMob(effect)
effect:move(2)
RPD.createLevelObject({
    kind="Deco",
    object_desc="Light"
}
,335)
local effect = RPD.MobFactory:mobByName("effects/Light")
effect:setPos(596)
RPD.Dungeon.level:spawnMob(effect)
effect:move(2)
RPD.createLevelObject({
    kind="Deco",
    object_desc="Light"
}
,596)
local effect = RPD.MobFactory:mobByName("effects/Light")
effect:setPos(358)
RPD.Dungeon.level:spawnMob(effect)
effect:move(2)
RPD.createLevelObject({
    kind="Deco",
    object_desc="Light"
}
,358)
local effect = RPD.MobFactory:mobByName("effects/Light")
effect:setPos(250)
RPD.Dungeon.level:spawnMob(effect)
effect:move(2)
RPD.createLevelObject({
    kind="Deco",
    object_desc="Light"
}
,250)
local effect = RPD.MobFactory:mobByName("effects/Light")
effect:setPos(787)
RPD.Dungeon.level:spawnMob(effect)
effect:move(2)
RPD.createLevelObject({
    kind="Deco",
    object_desc="Light"
}
,787)

        local levelSize = RPD.Dungeon.level:getLength()
        for i = 0 , levelSize - 1 do
            if RPD.Dungeon.level.solid[i] then
                local emitter = RPD.Sfx.CellEmitter:get(i)
                --emitter:pour(RPD.Sfx.SnowParticle.FACTORY, 2)
            end
        end

    end,
act = function()
if storage.get("multiplayer") then
Multiplayer.hero.receiveData()
end
return true
end
})