---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 04.08.18 18:14
---

local RPD = require "scripts/lib/epicClasses"

local actor = require "scripts/lib/actor"

return actor.init({
    actionTime = function()
        return 1
    end,
    activate = function()
RPD.GameScene:particleEffect("Candle", 90);
RPD.GameScene:particleEffect("Candle", 84);
RPD.GameScene:particleEffect("Candle", 308);
RPD.GameScene:particleEffect("Candle", 314);
        local levelSize = RPD.Dungeon.level:getLength()
        for i = 0 , levelSize - 1 do
            if RPD.Dungeon.level.map[i] == RPD.Terrain.EMPTY and math.random(1,5) == 1 then
                local emitter = RPD.Sfx.CellEmitter:get(i-1)
                emitter:pour(RPD.Sfx.WindParticle.FACTORY, 16)
                local levelSize = RPD.Dungeon.level:getLength()
              end
              local mob = RPD.Actor:findChar(i)
  if mob then
  mob:getSprite():tint(0,0,0,0.3)
  end

        end

    end

})
