local table = 
{
kind = "Castle",
Entrance = "BanditEntrance",
EntranceDebag = "EntranceDebag",
Exit = "BanditExit",
ExitHeigth = 4,
ExitWidth = 4,
RoomHeigth = 9,
RoomWidth = 9,
RandRooms = {"BanditHell","BanditHell2","GaurdMonkRoom","BanditGarden","BanditRoom2","BanditBigGarden","BanditBestRoom","BanditStatueRoom","BanditBestRoom","BanditKitchen","BigBanditArmory","BanditFishbowl","BanditArmory","BanditRoom1","BigBanditLibrary","BanditLibrary","BanditTomb","NightElfs"},
-- RandRooms = {"PrisonArmory"},
HasBase = false,
Items = {"Ration"},
Water = true,
WaterMin = 1,
WaterMax = 2,
WaterChanse = 0.0005,
Grass = true,
GrassChanse = 0.0001,
GrassMin = 1,
GrassMax = 2,
Traps = {
"ToxicTrap",
"FireTrap",
"PoisonTrap",
"AlaramTrap",
"GrippingTrap",
"LightingTrap",
"ParalyticTrap",
"SecretToxicTrap",
"SecretFireTrap",
"SecretPoisonTrap",
"SecretAlaramTrap",
"SecretGrippingTrap",
"SecretLightingTrap",
"SecretParalyticTrap"
},
ChanseTrap = 0.1,
Shop = "BanditShop",
LevelShop = 21,
ShopWidth = 7,
ShopHeigth = 7,
NPC = nil,
levelNPC = 22,
NPCRoom = "GnollPirateRoom",
NPCRoomWidth = 7,
NPCRoomHeigth = 7,
Range = 10000,
GinFactor = 20,
RoomFactor = 0,
MiniBoss = "ScoutRoom",
LevelMiniBoss = 23
}

return table
