---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTibuff.target: 25.03.19 0:06
---
local RPD  = require "scripts/lib/commonClasses"

local buff = require "scripts/lib/buff"

return buff.init{
    desc  = function ()
        return {
            icon          = 51,
            name         = RPD.textById("Darck_Mantel_Buff"),
            info          = "DieHard_Info",
        }
    end,
attachTo = function(self, buff, target)
return true
    end,
    detach = function(self, buff)
    end,
    act = function(self,buff)
        buff:detach()
end, 
   charAct = function(self,buff)
if math.random(1,4) == 1 and RPD.Dungeon.hero:getNearestEnemy() then
local x = RPD.Dungeon.level:cellX(buff.target:getPos())
local y = RPD.Dungeon.level:cellY(buff.target:getPos())
        for i = x - math.random(1,3), x + math.random(1,3) do
         for j = y - math.random(1,3), y + math.random(1,3) do
local pos = RPD.Dungeon.level:cell(i,j)
local soul =  RPD.Actor:findChar(pos-1)
if RPD.Dungeon.level.map[pos] == RPD.Terrain.EMPTY then
if soul and soul ~= buff.target then 
RPD.topEffect(pos-1,"ShadowTentacle")
soul:damage(math.random(25,60), buff.target)
 else
RPD.topEffect(pos-1,"ShadowTentacle")
end
end
end
end
else if RPD.Dungeon.hero:getNearestEnemy() and math.random(1,4) == 1 then
RPD.topEffect(RPD.Dungeon.hero:getPos()-RPD.Dungeon.level:getWidth()-1,"Void")
RPD.zapEffect(RPD.Dungeon.hero:getPos()-RPD.Dungeon.level:getWidth()-1, RPD.Dungeon.hero:getNearestEnemy():getPos(), "Shadow")
RPD.Dungeon.hero:getNearestEnemy():damage(math.random(2,4), RPD.Dungeon.hero)

RPD.topEffect(RPD.Dungeon.hero:getPos()-RPD.Dungeon.level:getWidth()+1,"Void")
RPD.zapEffect(RPD.Dungeon.hero:getPos()-RPD.Dungeon.level:getWidth()+1, RPD.Dungeon.hero:getNearestEnemy():getPos(), "Shadow")
RPD.Dungeon.hero:getNearestEnemy():damage(math.random(2,4), RPD.Dungeon.hero)

RPD.topEffect(RPD.Dungeon.hero:getPos()+RPD.Dungeon.level:getWidth()-1,"Void")
RPD.zapEffect(RPD.Dungeon.hero:getPos()+RPD.Dungeon.level:getWidth()-1, RPD.Dungeon.hero:getNearestEnemy():getPos(), "Shadow")
RPD.Dungeon.hero:getNearestEnemy():damage(math.random(2,4), RPD.Dungeon.hero)

RPD.topEffect(RPD.Dungeon.hero:getPos()+RPD.Dungeon.level:getWidth()+1,"Void")
RPD.zapEffect(RPD.Dungeon.hero:getPos()+RPD.Dungeon.level:getWidth()+1, RPD.Dungeon.hero:getNearestEnemy():getPos(), "Shadow")
RPD.Dungeon.hero:getNearestEnemy():damage(math.random(2,4), RPD.Dungeon.hero)
RPD.Dungeon.hero:spend(TIME_TO_ZAP)
end
end
end
}
