---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 25.03.19 0:06
---
local RPD  = require "scripts/lib/commonClasses"

local buff = require "scripts/lib/buff"


return buff.init{
    desc  = function ()
        return {
            icon          = 47,
            name          = "Огненное благословение",
            info          = "DieHard_Info",
        }
    end,
attachTo = function(self, buff, target)
return true
    end,
    detach = function(self, buff)
    end,
    act = function(self,buff)
        buff:detach()
end, 
    charAct = function(self,buff)

local levelSize = RPD.Dungeon.level:getLength()
        local cell = math.random(levelSize)-1
        if not RPD.Dungeon.level.solid[cell] then
            RPD.placeBlob( RPD.Blobs.Fire, cell, 10)
            RPD.zapEffect(buff.target:getPos(), cell, "Fire")
        return true
end
        buff:spend(1)
end
}
