---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 25.03.19 0:06
---
local RPD  = require "scripts/lib/commonClasses"

local buff = require "scripts/lib/buff"


return buff.init{
    desc  = function ()
        return {
            icon          = 49,
            name          = "Жадность",
            info          = "DieHard_Info",
        }
    end,
attachTo = function(self, buff, target)
return true
    end,
    detach = function(self, buff)
    end,
   charAct = function(self,buff)
buff:spend(10)
buff.target:getSprite():emitter():start(RPD.Sfx.Speck:factory( RPD.Sfx.Speck.COIN), 0.1,4);
if buff.target:gold() >= 100 then
buff.target:spendGold(100)
end
end,
act = function(self,buff)
buff:detach()
end
}
