---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 02.05.19 14:36
---
local RPD  = require "scripts/lib/epicClasses"

local buff = require "scripts/lib/buff"


return buff.init{
    desc  = function ()
        return {
            icon          = -1,
            name          = "CloakBuff_Name",
            info          = "CloakBuff_Info",
        }
    end,

attachTo = function(self)
return true
end,

detach = function(self, buff)
end,

act = function(self,buff)
buff:detach()
end,

defenceProc = function(self, buff, enemy, damage)
--RPD.glog("defenceProc:"..buff:name()..":"..buff.target:name().." was attacked by "..enemy:name().." for ".. tostring(damage).. " points of raw damage")
return damage-(buff:level())
end,

--[[
charAct = function(self,buff)
if buff.target:getBelongings().ring1 ~= nil and buff.target:getBelongings().ring2 ~= nil then
RPD.glog("-- Ты неможешь носить оружие таким образом.")
RPD.Dungeon.level:drop(buff.target:getBelongings().ring1,buff.target:getPos())
RPD.Dungeon.level:drop(buff.target:getBelongings().ring2,buff.target:getPos())
buff.target:getBelongings().ring1:removeItemFrom(buff.target)
buff.target:getBelongings().ring2:removeItemFrom(buff.target)
end
end
--]]
}
