---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 25.03.19 0:06
---
local RPD  = require "scripts/lib/commonClasses"

local buff = require "scripts/lib/buff"

return buff.init{
    desc  = function ()
        return {
            icon          = -1,
            name          = "Путь исправления",
            info          = "DieHardBuff_Info",
        }
    end,
attachTo = function(self, buff, target)
RPD.permanentBuff(buff.target,RPD.Buffs.Light)
--buff.target:getSprite():emitter():start(RPD.Sfx.ElmoParticle.FACTORY, 0.08);
return true
    end,
    detach = function(self, buff)
RPD.removeBuff(buff.target,RPD.Buffs.Light)
--buff.target:getSprite():emitter():stop(RPD.Sfx.ElmoParticle.FACTORY, 0.08);
    end,
    act = function(self,buff)
buff:detach()
end, 
    charAct = function(enemy,buff,self)
buff:spend(1)
buff.target:damage(math.random(RPD.Dungeon.hero:lvl()+1,RPD.Dungeon.depth),RPD.Dungeon.hero)
end
}