local table = 
{
kind = "Caves",
Entrance = "CavesEntrance",
EntranceDebag = "EntranceDebag",
Exit = "CavesExit",
ExitHeigth = 4,
ExitWidth = 4,
RoomHeigth = 7,
RoomWidth = 7, 
RandRooms = {"Cave","BigCave","ChasmCave","CavesWarehouse","CenterCave","SmallCave","RatCave","RatCave","RatCave","EmptyWell","CavesCastleHall","CavesCastleChasm","BatNest","CavesCastleCrystal","SpinnerNest","CavesTomb","GoldenCave","BigGoldenCave"},
--RandRooms = {"SpinnerNest"},
HasBase = false,
Items = {"Ration"},
Water = true,
WaterMin = 1,
WaterMax = 3,
WaterChanse = 0.0005,
Grass = true,
GrassChanse = 0.0001,
GrassMin = 1,
GrassMax = 3,
Traps = {
"ToxicTrap",
"FireTrap",
"PoisonTrap",
"AlaramTrap",
"GrippingTrap",
"LightingTrap",
"ParalyticTrap",
"SecretToxicTrap",
"SecretFireTrap",
"SecretPoisonTrap",
"SecretAlaramTrap",
"SecretGrippingTrap",
"SecretLightingTrap",
"SecretParalyticTrap"
},
ChanseTrap = 0.1,
Shop = "CavesShop",
LevelShop = 11,
ShopWidth = 7,
ShopHeigth = 7,
NPC = nil,
levelNPC = 14,
NPCRoom = "BlacksmithRoom",
NPCRoomWidth = 7,
NPCRoomHeigth = 7,
Range = 10000,
GinFactor = 20,
RoomFactor = 0,
MiniBoss = "DM50Room",
LevelMiniBoss = 13
}

return table
