local table = 
{
kind = "Castle",
Entrance = "HallCastleEntrance",
EntranceDebag = "HallCastleEntrance",
Exit = "Exit",
ExitHeigth = 9,
ExitWidth = 9,
RoomHeigth = 9,
RoomWidth = 9,
RandRooms = {"HallCastleLibrary","HallCastleRoom","BigHallCastleRoom","SmallHallCastleRoom","FireNefritNest","DarkLibrary","OldTemple","HallCastleGarden","HallCastleAlhimy","HallCastleGuards","HallCastleFireGuards","HallCastleRedGarden","HallCastleBlueGarden","HallCastleFishbowl","HallCastleWell","HallCastleRoomGarden","ShadowSpiderNest"},
-- RandRooms = {"PrisonArmory"},
HasBase = true,
Items = {"Ration"},
Water = true,
WaterMin = 0,
WaterMax = 1,
WaterChanse = 0.0005,
Grass = true,
GrassChanse = 0.0001,
GrassMin = 0,
GrassMax = 1,
Traps = {
"ToxicTrap",
"FireTrap",
"PoisonTrap",
"AlaramTrap",
"GrippingTrap",
"LightingTrap",
"ParalyticTrap",
"SecretToxicTrap",
"SecretFireTrap",
"SecretPoisonTrap",
"SecretAlaramTrap",
"SecretGrippingTrap",
"SecretLightingTrap",
"SecretParalyticTrap"
},
ChanseTrap = 0.1,
Shop = "HallCastleShop",
LevelShop = 31,
ShopWidth = 7,
ShopHeigth = 7,
NPC = nil,
levelNPC = 31,
NPCRoom = nil,
NPCRoomWidth = 7,
NPCRoomHeigth = 7,
Range = 10000,
GinFactor = 10,
RoomFactor = 0,
MiniBoss = {"LordRoom"},
LevelMiniBoss = 31
}

return table