local table = 
{
kind = "Caves",
Entrance = "CavesEntrance",
EntranceDebag = "EntranceDebag",
Exit = "CavesExit",
ExitHeigth = 4,
ExitWidth = 4,
RoomHeigth = 7,
RoomWidth = 7, 
RandRooms = {"IceBigCave","SmallCave","IceCave","IceLibrary","IceAlhimy","IceRiches","IceRiches","IceRiches","IceRiches","IceArmory","FrozenGnolls","IceVerticalCave","IceTemple","IceRoomHorizontal","IceCavesStatue","IceCrystal","IceNecropolis","IceNefritCastle","ThimogorsCastle","IceTomb","IceFishbowl"},
--RandRooms = {"IceNefritCastle"},
HasBase = false,
Items = {"Ration"},
Water = true,
WaterMin = 1,
WaterMax = 3,
WaterChanse = 0.0007,
Grass = true,
GrassChanse = 0.00005,
GrassMin = 1,
GrassMax = 3,
Traps = {
"ToxicTrap",
"FireTrap",
"PoisonTrap",
"AlaramTrap",
"GrippingTrap",
"LightingTrap",
"ParalyticTrap",
"SecretToxicTrap",
"SecretFireTrap",
"SecretPoisonTrap",
"SecretAlaramTrap",
"SecretGrippingTrap",
"SecretLightingTrap",
"SecretParalyticTrap"
},
ChanseTrap = 0.1,
Shop = "IceShop",
LevelShop = 16,
ShopWidth = 7,
ShopHeigth = 7,
NPC = nil,
levelNPC = 19,
NPCRoom = "CagedKoboltRoom",
NPCRoomWidth = 7,
NPCRoomHeigth = 7,
Range = 10000,
GinFactor = 20,
RoomFactor = 0,
MiniBoss = {"LloydRoom"},
LevelMiniBoss = 18
}

return table
