local table = 
{
kind = "Town",
Entrance = "NightEntrance",
EntranceDebag = "EntranceDebag",
Exit = "CityExit",
ExitHeigth = 4,
ExitWidth = 4,
RoomHeigth = 11,
RoomWidth = 11,
RandRooms = {"Alchimy","CrystalStatues1","CrystalStatues2","CrystalStatues3","CrystalStatues4","CrystalStatues5","EpicLibrary","Fishbowl","Ghost","HomeLeft","HomeRight","Library","Portal","Statues","Warehouse"},
HasBase = false,
Items = {"Ration"},
Water = true,
WaterMin = 1,
WaterMax = 3,
WaterChanse = 0.0005,
Grass = true,
GrassChanse = 0.0001,
GrassMin = 1,
GrassMax = 2,
Traps = {
"ToxicTrap",
"FireTrap",
"PoisonTrap",
"AlaramTrap",
"GrippingTrap",
"LightingTrap",
"ParalyticTrap",
"SecretToxicTrap",
"SecretFireTrap",
"SecretPoisonTrap",
"SecretAlaramTrap",
"SecretGrippingTrap",
"SecretLightingTrap",
"SecretParalyticTrap"
},
ChanseTrap = 0.1,
Chanse = 1,
Shop = "CityShop",
LevelShop = 16,
ShopWidth = 9,
ShopHeigth = 9,
NPC = nil,
levelNPC = 17,
NPCRoom = "CityPortal",
NPCRoomWidth = 7,
NPCRoomHeigth = 7,
Range = 10000,
GinFactor = 20,
RoomFactor = 0,
MiniBoss = nil,
LevelMiniBoss = nil
}

return table