---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 23.08.18 22:51
---

local RPD = require "scripts/lib/commonClasses"

local ai = require "scripts/lib/ai"

return ai.init{

    act       = function(self, ai, me)
if math.random(1,6) == 1 then
me:spend(1)
for i = 0,RPD.Dungeon.level:getLength()-1 do            
    if RPD.Dungeon.level.map[i] == RPD.Terrain.STATUE then
RPD.zapEffect(i-1,RPD.Dungeon.hero:getPos(),"Dart");
RPD.Dungeon.hero:damage(math.random(1,3),me)
    end
end

else if math.random(1,3) == 2 then
for i=1,3 do
local level = RPD.Dungeon.level
local x = level:cellX(me:getPos())
local y = level:cellY(me:getPos())
        for i = x - 4, x + 4 do
         for j = y - 4, y + 4 do
local pos = level:cell(i,j)
local soul =  RPD.Actor:findChar(pos-1)
if level.map[pos] == RPD.Terrain.EMPTY then
if math.random(1,3) == 3 then
if soul and soul ~= me then 
RPD.topEffect(pos-1,"Klak")
soul:damage(math.random(1,10), me)
 else
RPD.topEffect(pos-1,"Klak")
end
end
end
end
end
me:spend(1)
end
else
local victim = RPD.Dungeon.hero
victim:damage(math.random(10,20), me)
RPD.Sfx.Wound:hit(victim)
RPD.playSound("dash.mp3")
RPD.zapEffect(me:getPos(),RPD.Dungeon.hero:getPos(),"dash")
me:getSprite():move(me:getPos(),RPD.Dungeon.hero:getPos())
me:move(RPD.Dungeon.hero:getPos())
me:spend(3)

end
end
end,

    gotDamage = function(self, ai, me, src, dmg)

    end,

    status = function(self, ai, me)
        return RPD.textById("attack_on_you")
    end
}