---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 23.08.18 22:51
---

local RPD = require "scripts/lib/commonClasses"

local ai = require "scripts/lib/ai"

dst = 0

return ai.init{

    act       = function(me, ai, me)
--[[
for i = 1, RPD.Dungeon.level:getLength()-1 do
local maybeMob = RPD.Actor:findChar(i)          
if maybeMob and maybeMob ~= RPD.Dungeon.hero and maybeMob:ht() == 76 then
if RPD.Dungeon.level:distance(me:getPos(),i) == 1 then
maybeMob:damage(math.random(30,60),me)
me:getSprite():attack(i-1)
--RPD.topEffect(i,"Debag")
me:spend(1)
break
else
me:beckon(i)
--RPD.topEffect(i,"Debag")
--me:spend(1)
break
end
end
if i == RPD.Dungeon.level:getLength()-2 then
me:spend(1)
end
end getNearestEnemy
--]]

for i = 1, RPD.Dungeon.level:getLength()-1 do
local maybeMob = RPD.Actor:findChar(i)        
dstr = dst
if maybeMob and maybeMob ~= RPD.Dungeon.hero and maybeMob:ht() == 76 then
dst = RPD.Dungeon.level:distance(me:getPos(),i)
if dst < dstr then
dstr = dst
self = maybeMob
end
end
end


if self then
if RPD.Dungeon.level:distance(me:getPos(),self:getPos() ) == 1 then
self:damage(math.random(30,60),me)
me:getSprite():attack(self:getPos() )
RPD.playSound( "snd_hit.ogg" )

for i = 1, RPD.Dungeon.level:getLength()-1 do
local maybeMob = RPD.Actor:findChar(i)        
if maybeMob and maybeMob ~= RPD.Dungeon.hero and maybeMob:ht() == 76 then
break
end
if i == RPD.Dungeon.level:getLength()-2 then
self = false
end
end

--RPD.topEffect(i,"Debag")
me:spend(1)
else
me:beckon(self:getPos())
--RPD.topEffect(i,"Debag")
--me:spend(1)
end
else
me:getSprite():idle()
me:spend(1)
end

end,

    gotDamage = function(me, ai, me, src, dmg)
end,

    status = function(me, ai, me)
        return "атакует"
    end
}