---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 23.08.18 22:51
---

local RPD = require "scripts/lib/commonClasses"

local ai = require "scripts/lib/ai"

return ai.init{

    act       = function(me, ai, me)
if math.random(1,3) == 1 then
cell = RPD.Ballistica:cast(me:getPos(),RPD.Dungeon.hero:getPos(),true,true,true)
me:getSprite():zap(cell)
if RPD.Actor:findChar(cell) then
RPD.Actor:findChar(cell):damage(math.random(10,20),me)
RPD.zapEffect(me:getPos(),cell,"Ice")
--RPD.affectBuff(RPD.Actor:findChar(cell),RPD.Buffs.Slow,math.random(1,4))
end
me:spend(3)
elseif math.random(1,3) == 1 then
me:getSprite():zap(me:getPos())
local level = RPD.Dungeon.level
local x = level:cellX(me:getPos())
local y = level:cellY(me:getPos())
        for i = x - 1, x + 1 do
         for j = y - 1, y + 1 do
local pos = level:cell(i,j)
if pos ~= me:getPos() then
RPD.placePseudoBlob( RPD.PseudoBlobs.Freezing, pos)
end
end
end
me:spend(4)
elseif math.random(1,10) == 1 then
for i = 1, RPD.Dungeon.level:getLength()-1 do
local maybeMob = RPD.Actor:findChar(i)        
if maybeMob and maybeMob ~= RPD.Dungeon.hero and maybeMob:ht() == 180 then
for i = 1,math.random(1,3) do
local pos = RPD.Dungeon.level:getEmptyCellNextTo(maybeMob:getPos())
if (RPD.Dungeon.level:cellValid(pos)) then
local mob = RPD.MobFactory:mobByName("IceSkeleton") 
mob:setPos(pos)
RPD.Dungeon.level:spawnMob(mob)
mob:getSprite():emitter():burst(RPD.Sfx.Speck:factory(RPD.Sfx.Speck.BONE ), 7);
me:getSprite():zap(me:getPos())
me:spend(5)
maybeMob:spend(1)
RPD.affectBuff(maybeMob, RPD.Buffs.Invisibility,3)
maybeMob:spend(3)
end
end
end
end
end

end,

    gotDamage = function(me, ai, me, src, dmg)
end,

    status = function(me, ai, me)
        return "охотится на тебя."
    end
}