---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 23.08.18 22:51
---

local RPD = require "scripts/lib/epicClasses"

local ai = require "scripts/lib/ai"

dst = 0

--nearestSelf = me

return ai.init{

    act       = function(me, ai, me)
dstr = 0
--dst = 0
--[[
for i = 1, RPD.Dungeon.level:getLength()-1 do
local maybeMob = RPD.Actor:findChar(i)          
if maybeMob and maybeMob ~= RPD.Dungeon.hero and maybeMob:ht() == 76 then
if RPD.Dungeon.level:distance(me:getPos(),i) == 1 then
maybeMob:damage(math.random(30,60),me)
me:getSprite():attack(i-1)
--RPD.topEffect(i,"Debag")
me:spend(1)
break
else
me:beckon(i)
--RPD.topEffect(i,"Debag")
--me:spend(1)
break
end
end
if i == RPD.Dungeon.level:getLength()-2 then
me:spend(1)
end  == RPD.Actor:findChar(RPD.Ballistica:cast(me:getPos(),nearestSelf:getPos(),true,true,true))  
end getNearestEnemy
--]]



for i = 1, RPD.Dungeon.level:getLength()-1 do
local maybeMob = RPD.Actor:findChar(i)        
dstr = dst
if maybeMob and maybeMob ~= RPD.Dungeon.hero and maybeMob ~= me then
dst = RPD.Dungeon.level:distance(me:getPos(),i)
if dst < dstr then
dstr = dst
nearestSelf = maybeMob
end
end
end
mob = nearestSelf

--for i = 1, RPD.Dungeon.level:getLength()-1 do
if mob and mob ~= me and mob   == RPD.Actor:findChar(RPD.Ballistica:cast(me:getPos(),nearestSelf:getPos(),true,true,true))   then
if RPD.Dungeon.level:distance(me:getPos(),mob:getPos() ) == 1 and  mob ~= me then
mob:damage(math.random(3,6),me)
me:getSprite():attack(mob:getPos() )
RPD.playSound( "snd_hit.ogg" )

for i = 1, RPD.Dungeon.level:getLength()-1 do
local maybeMob = RPD.Actor:findChar(i)        
if mob then
break
end
if i == RPD.Dungeon.level:getLength()-2 then
for i = 1, RPD.Dungeon.level:getLength()-1 do
local maybeMob = RPD.Actor:findChar(i)        
dstr = dst
if maybeMob and maybeMob ~= RPD.Dungeon.hero and maybeMob ~= me then
dst = RPD.Dungeon.level:distance(me:getPos(),i)
if dst < dstr then
dstr = dst
nearestSelf = maybeMob
end
end
end

mob = nearestSelf
end
end
 
RPD.topEffect(mob:getPos(),"Debag")
me:spend(1)
else
me:beckon(mob:getPos())
RPD.topEffect(mob:getPos(),"Debag")
--me:spend(1)
end
else
me:getSprite():idle()
me:spend(1)
end
--end
end,

    gotDamage = function(me, ai, me, src, dmg)
end,

    status = function(me, ai, me)
        return RPD.StringsManager:maybeId("attack_on_you")
    end
}