---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 23.08.18 22:51
---

local RPD = require "scripts/lib/commonClasses"

local ai = require "scripts/lib/ai"

local storage = require "scripts/lib/storage"

return ai.init{

act       = function(me, ai, me)

summonRats = function()
local rats = {
"RatGuard",
"RatMage",
"RatArcher"
}
if math.random(1,2) == 1 then
RPD.playSound( "snd_lullaby.mp3" )
else
RPD.playSound( "snd_dominance.mp3")
end
local level = RPD.Dungeon.level
local hero = RPD.Dungeon.hero
for i = 1,math.random(1,4) do
local mob = RPD.MobFactory:mobByName(rats[math.random(1,#rats)])
local pos = level:getEmptyCellNextTo(me:getPos())
if (level:cellValid(pos)) then
mob:setPos(pos)
level:spawnMob(RPD.Mob:makePet(mob,RPD.Dungeon.hero),0,me:getPos())
RPD.Sfx.SpellSprite:show(me, RPD.Sfx.SpellSprite.SUMMON)
end
end
me:destroy()
me:getSprite():killAndErase()
RPD.topEffect(me:getPos(),"BlueMagicCould")
end

me:spend(2)
summonRats()

end,

    gotDamage = function(me, ai, me, src, dmg)
end,

    status = function(me, ai, me)
        return RPD.textById("sing")
    end
}