---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 23.08.18 22:51
---

local RPD = require "scripts/lib/commonClasses"

local ai = require "scripts/lib/ai"

return ai.init{

act       = function(self, ai, me)

addRay = function()
local level = RPD.Dungeon.level

ray = function(cell)
local from = me:getPos()
local to = RPD.Ballistica:cast(from,cell,true,true,true)
local enemy = RPD.Actor:findChar(to)
RPD.zapEffect(from,to,"DeathRay")
if enemy and enemy ~= me then
enemy:damage(math.random(20,35),me)
end
end

f = math.random(1,3)
local x = level:cellX(me:getPos())
local y = level:cellY(me:getPos())
for i = x - f, x + f do
for j = y - f, y + f do
local pos = RPD.Dungeon.level:cell(i,j)
--if level.map[pos] == RPD.Terrain.EMPTY then
ray(pos)
--end
end
end
--me:getSprite():idle()
me:getSprite():dummyAttack()
end

if level:distance(RPD.Dungeon.hero:getPos(),me:getPos()) < 4 then
addRay()
me:spend(2)
else
me:spend(1)
end

end,

    gotDamage = function(self, ai, me, src, dmg)

    end,

    status = function(self, ai, me)
        return RPD.textById("attack_on_you")
    end
}