
---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 4/1/20 8:29 PM
---


local RPD = require "scripts/lib/epicClasses"

local item = require "scripts/lib/item"

return item.init{
    desc  = function ()
        return {
            image     = 9,
            imageFile = "items/swords.png",
            name      = RPD.StringsManager:maybeId("Epee_Name"),
            info      = RPD.StringsManager:maybeId("Epee_Info"),
            price     = 17,
            equipable = RPD.Slots.weapon
        }
    end,

    goodForMelee = function()
        return true
    end,

    getVisualName = function()
        return "Epee"
    end,

    getAttackAnimationClass = function()
         return "sword"
    end,

    slot = function(self, item, belongings)
        return RPD.Slots.weapon
    end,

    accuracyFactor    = function(self, item, user)
        return 2
    end,

    typicalSTR  = function(self, item)
            return math.max(1,14 - item:level())
    end,

     requiredSTR = function(self, item)
            return math.max(1,14 - item:level())
     end,

    damageRoll        = function(self, item, user)
        local lvl = item:level()
        return math.random(3, 16+lvl*3)
    end,

    attackDelayFactor = function(self, item, user)
        return 0.5
    end,

    isFliesStraight = function(self, item)
        return true
    end
}
