---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 10/20/19 10:35 PM
---

local RPD  = require "scripts/lib/commonClasses"

local buff = require "scripts/lib/buff"

local spells = {
DarkSperal = {"S","S2","S3","S4"},
YellowSperal = {"A1","A2","A3","A4"},
TombPiece = {"B1","B2","B3","B4"},
BluePitch = {"C1","C2","C3","C4"},
Quartz = {"D1","D2","D3","D4"},
SpiderHelmet = {"I1","I2","I3","I4"},
DworfSkull = {"F1","F2","F3","F4"},
HandmadeCrystal = {"J1","J2","J3","J4"}
}

return buff.init{
desc  = function ()
        return {
            icon          = -1,
            name          = RPD.StringsManager:maybeId("Water_Regeneration_Buff"),
            info          = "DieHard_Info",
        }
    end,
attachTo = function(self, buff, target)
return true
    end,
    detach = function(self, buff)
    end,
    act = function(self,buff)
        buff:detach()
end, 
   charAct = function(self,buff)
buff.target:getSprite():tint(0,1,201/255,0.5)
end
}