---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 21.03.19 22:57
---
---

local RPD = require "scripts/lib/epicClasses"

local spell = require "scripts/lib/spell"

return spell.init{
    desc  = function ()
        return {
            image         = 5,
            imageFile     = "spellsIcons/necromancy.png",
            name          = RPD.StringsManager:maybeId("SummonSoul_Name"),
            info          = RPD.StringsManager:maybeId("SummonSoul_Info"),
            magicAffinity = "Combat",
            targetingType = "self",          level         = 2,
            spellCost     = 7,
            cooldown      = 5,
            castTime      = 2
        }
    end,
    cast = function(self, spell, chr,caster,cell)
        local level = RPD.Dungeon.level

        local hero = RPD.Dungeon.hero
            local mob = RPD.mob("EnslavedSoul")
            local pos = level:getEmptyCellNextTo(hero:getPos())
            if (level:cellValid(pos)) then
                mob:setPos(pos)
level:spawnMob(RPD.Mob:makePet(mob,hero));
        mob:getSprite():emitter():burst( RPD.Sfx.ShadowParticle.CURSE, 6 )

    end
return true
end
}
